/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_text_input (XDR *xdrs, text_input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->text, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
