/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTOCOL_H_RPCGEN
#define _PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct text_input {
	char *text;
	int offset;
};
typedef struct text_input text_input;

#define PROTOCOL_PROG 0x33113377
#define PROTOCOL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPPERCASE 1
extern  char ** uppercase_1(text_input *, CLIENT *);
extern  char ** uppercase_1_svc(text_input *, struct svc_req *);
#define LOWERCASE 2
extern  char ** lowercase_1(text_input *, CLIENT *);
extern  char ** lowercase_1_svc(text_input *, struct svc_req *);
#define ROT 3
extern  char ** rot_1(text_input *, CLIENT *);
extern  char ** rot_1_svc(text_input *, struct svc_req *);
#define UNROT 4
extern  char ** unrot_1(text_input *, CLIENT *);
extern  char ** unrot_1_svc(text_input *, struct svc_req *);
extern int protocol_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPPERCASE 1
extern  char ** uppercase_1();
extern  char ** uppercase_1_svc();
#define LOWERCASE 2
extern  char ** lowercase_1();
extern  char ** lowercase_1_svc();
#define ROT 3
extern  char ** rot_1();
extern  char ** rot_1_svc();
#define UNROT 4
extern  char ** unrot_1();
extern  char ** unrot_1_svc();
extern int protocol_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_text_input (XDR *, text_input*);

#else /* K&R C */
extern bool_t xdr_text_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTOCOL_H_RPCGEN */
