/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pi_calculator.h"

bool_t
xdr_interval (XDR *xdrs, interval *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}
