/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PI_CALCULATOR_H_RPCGEN
#define _PI_CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct interval {
	int n;
};
typedef struct interval interval;

#define PI_CALCULATOR_PROG 0x33337711
#define PI_CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE_PI 1
extern  double * calculate_pi_1(interval *, CLIENT *);
extern  double * calculate_pi_1_svc(interval *, struct svc_req *);
extern int pi_calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE_PI 1
extern  double * calculate_pi_1();
extern  double * calculate_pi_1_svc();
extern int pi_calculator_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_interval (XDR *, interval*);

#else /* K&R C */
extern bool_t xdr_interval ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PI_CALCULATOR_H_RPCGEN */
